services:
  - type: web
    name: bernardo-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://cjgbernardo21_db_user:WetCarbon123@cluster0.ztwks0s.mongodb.net/wetcarbon?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: sampleSecret